{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  labels:
    {{- with .Values.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
      {{- include "helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "helm.serviceAccountName" . }}-rolebinding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.serviceAccount.binding.roleName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helm.serviceAccountName" . }}
  {{- end }}
