= Event Publisher API

== What does it do
The Event Publisher Api is made to support IGW in sending events into Azure Event Hub. They will provide us with one type of event and it will be published on one topic.

== How to use it
The API has at the moment one endpoint, below you will see an example of a call to this endpoint.

=== The request
[source,httprequest]
----
POST https://api.sit.atradiusnet.com/sc/platforms/events/v1/publish-igw-event
Content-Type: application/json

{
  "event_name": "My IGW event 496",<1>
  "event_uuid": "cd92d795-9e73-497a-8185-b9411c89c879",<2>
  "event_domain": "IGW Domain",<3>
  "event_type": "IGW create test",<4>
  "event_subtype": "CREATE",<5>
  "event_datetime": "2023-08-16T13:38:32.119893500Z",<6>
  "event_origin_id": "IGW",<7>
  "object_type": "CLD",<8>
  "object_id": "921",<9>
  "correlation_id": "5e3be7c8-902d-4d23-8735-b2bea3055ba9",<10>
  "resources": { <11>
    "igwEvent": "41241"
  },
  "payload": { <12>
    "igwMessage": "Testing Message"
  }
}
----
<1> The name of the event.
<2> The UUID of an event, *if omitted*, then it's generated by the API.
<3> Event Domain, the domain the event is generated from.
<4> The type of the event.
<5> The Sub type of the event.
<6> The datetime the event was created, or the related action was executed. *if omitted*, the time of it arriving at the API will be used for putting it on Event hub.
<7> Event origin id, the ID of the system creating the event.
<8> The object type that the event occurred for.
<9> The id of the object the event occurred for.
<10> The Atradius Correlation Id, used to track activities throughout the landscape.
<11> The resource it must be key value pairs where the key is ALWAYS a String. It's used to refer to object related to this event.
<12> The Payload of the event. It must always be of the same model for the above specified Event Type and Event Subtype!

=== The response

When the event is successfully published to Event Hub the HTTP status code will be a *201 Created*.

When the request does not adhere to the specified schema, a *400 Bad Request* with be returned, with some information of what is wrong.

When problem occurs with the connection to Event Hub, or an error is returned from Event Hub, a *502 Bad Gateway* is returned equally with information of the error.

Finally if the action of sending the event to Event Hub takes too long (Currently set at 30 seconds) a *504 Gateway Timeout* is returned.