# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: acritsdevops.azurecr.io/sc-org/event-publisher-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

serviceAccount:
  labels:
    azure.workload.identity/use: "true"
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    azure.workload.identity/client-id: "fa125719-a358-47de-8805-2242ef5716b4"
  # The name of the service account to use.
  name: event-publish-api-svc
  #TODO: Rename in next iteration as name: event-publisher-svc
  # If not set and create is true, a name is generated using the fullname template
  binding:
    roleName: "aks-service"

container:
  port: 8080
  managementPort: 8081
  context: ""

ingress:
  enabled: true
  className: nginx
  host: apps.sit.sc.atradiusnet.com
  tls:
    - hosts:
        - apps.sit.sc.atradiusnet.com
      secretName: sc-weu-sit-ingress-ssl
  annotations:
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/sc/platforms/events"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  http:
    paths:
      - path: /sc/platforms/events(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: event-publisher-service
            port:
              number: 80
deployment:
  template:
    labels:
      custom.log.label: json
      azure.workload.identity/use: "true"
  spec:
    revisionHistoryLimit: 1
  container:
    env:
      - name: spring.profiles.active
        value: azure,docker
      - name: EventHubNamespace
        value: sc-weu-sit-eventhub-ns
      - name: SharedAccessKeyName
        value: event-framework-publish-api
        #TODO: Rename in next iteration as value: event-publisher
      - name: atradius.igw.publish.topic-name
        value: sc-weu-sit-igw-events
      - name: ATRADIUS_OIDM_DOMAIN_NAME
        value: DEV_JET_WebGateDomain
      - name: ATRADIUS_OIDM_VALIDATION_TOKEN_URL
        value: https://login-dev.atradiusnet.com/oauth2/rest/token/info
      - name: ANDROMEDA_AUTH_PERMIT_ALL
        value: /actuator/**
      - name: ENVIRONMENT
        value: sit
      - name: ELASTICSEARCH_SERVER_URL
        value: https://3932171ec801482a9fbe9924508ba392.apm.uksouth.azure.elastic-cloud.com:443
      - name: ELASTICSEARCH_TOKEN
        value: MhRHz75B0440z7Q29w
    volumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-tls"
secrets:
  - name: SharedAccessKey
    secret: eventframeworksecret
    #TODO: Rename in next iteration as secret: eventPublisherSecret
    key: token


resources: { }
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }
